# Generated by Django 3.2.5 on 2021-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_stock_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bloodgroup',
            field=models.CharField(max_length=20),
        ),
    ]
