# Generated by Django 3.2.5 on 2021-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0003_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='requests',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
