# Generated by Django 3.1.6 on 2021-07-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0005_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='notes',
        ),
    ]
